name: Deploy job_scraper to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.2'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Package Lambda function
      run: |
        mkdir -p package
        cp job_scraper.py package/
        pip install -r requirements.txt --target package/
        cd package
        zip -r ../job_scraper.zip .
      shell: bash

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: Deploy to AWS Lambda
      run: |
        aws lambda update-function-code --function-name jobScraper --zip-file fileb://job_scraper.zip
      shell: bash
